name: release
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: build
        run: ./gradlew build

      - name: publish
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: PxIvFRZv
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: false

          changelog: ${{github.event.head_commit.message}}

          github-token: ${{ secrets.GITHUB_TOKEN }}